<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Ошибка сервиса</title>
    <link rel="icon" href="${contextPath}/images/vision.png">
    <link rel="stylesheet" href="${contextPath}/css/header.css">
    <link rel="stylesheet" href="${contextPath}/css/error.css">
</head>
<body>

<main class="main">
    <div class="main__content">
        <div class="error">
            <img class="error__image" src="${contextPath}/images/serviceUnavaliable.png" alt="Сервис недоступен">
            <h2 class="error__title">Сервис временно недоступен</h2>
            <p class="error__text">Попробуйте зайти позже.</p>
            <a class="error__link" href="${contextPath}">На главную</a>
        </div>
    </div>
</main>

</body>
</html>